program: run-early.py
metric:
  name: Cross-Validation Metrics Dict/weighted_score_mean
  goal: maximize

method: bayes
parameters:
  kappa_scale:
    distribution: uniform
    min: 1.0
    max: 1.08
  lr_scale:
    distribution: q_log_uniform_values
    min: 1.0
    max: 1.15
    q: 1e-2
  eps_scale:
    distribution: uniform
    min: 3.0
    max: 8.0
  beta1_scale:
    distribution: uniform
    min: 0.90
    max: 1.0
  beta2_scale:
    distribution: uniform
    min: 0.99
    max: 1.02
  delta:
    distribution: uniform
    min: 0
    max: 0.2
  batch_size:
    values: [412,825,1648]
  linearization_type:
    values: ['linear']
  # resize:
  #   values: [true, false]
early_terminate:
  type: hyperband
  max_iter: 256
  eta: 2
  s: 5
command:
- ${env}
- ${interpreter}
- ${program}
- ${args}
